# Generated by Django 3.1.6 on 2021-02-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_client', '0006_prescription_is_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='order_status',
            field=models.SmallIntegerField(default=0, verbose_name='状态 未推送0-推送成功-1-取消推送99-推送失败>1'),
        ),
    ]
